config/routes.rb
# Plugin's routes
# See: http://guides.rubyonrails.org/routing.html
# get 'tracker/action', to: 'tracker_management_actions#new'
get 'tracker/actions', to: 'tracker_management_actions#index'
get 'tracker/options/:type', to: 'tracker_management_actions#options'
# post 'create/tracker/actions',to: 'tracker_management_actions#create'
post 'create/csvfile/tracker',to: 'tracker_management_actions#create_trecker'

app/controllers/tracker_management_actions_controller.rb
class TrackerManagementActionsController < ApplicationController
	# before_action :check_user, only:[:show]
	require 'csv'    
	require 'aws-sdk-sqs'  # v2: require 'aws-sdk'

	def index
		@projects = Project.select(:id,:name)
	end

	def tracker_log
		@@tracker_log ||= Logger.new("#{Rails.root}/log/tracker_bulk_upload.log")
	end

	# def show
	# 	# @projects = Project.select(:id,:name)
	# end

	# def new
	# 	@projects = Project.select(:id,:name)
	# 	@tracker_action = TrackerManagementAction.new()
	# end

	# def create
	# 	@projects = Project.select(:id,:name)
	# 	@tracker_action = TrackerManagementAction.new(tracker_action_params)
	# 	if @tracker_action.save
	# 		flash[:success] = "Action created successfuly!!"
	# 		redirect_to tracker_actions_path
	# 	else
	# 		@tracker_action.errors.full_messages.each{|a| flash[:errors] = a} 
	# 		render :new
	# 	end	
	# end

	def create_trecker
		@projects = Project.select(:id,:name)
		project_id = tracker_action_params['project_id']
		tracker_log.info("======> project id:  #{project_id} <=========")
		tracker_id = tracker_action_params['tracker_id']
		tracker_log.info("======> tracker id:  #{tracker_id} <=========")
		parent_id = tracker_action_params['parent_id']
		tracker_log.info("======> Parent issue id:  #{parent_id} <=========")
		@tracker = Tracker.find_by_id(tracker_id)
		tracker_log.info("======> Tracker:  #{@tracker} <=========")


		@errors = {message:[],column_missing:[],data_missing:[]}
		if params[:tracker_action][:file].present? && !project_id.blank? && !@tracker.nil?
			@users = User.select(:id,:firstname,:lastname,:login)
			@categories = IssueCategory.select(:id,:name)
			@priorities = IssuePriority.select(:id,:name)
			@issue_status = IssueStatus.select(:id,:name)

			tracker_log.info("======> Inside the CSV file functionality <=========")
			csv_text = File.read(params[:tracker_action][:file].path)
			csv = CSV.parse(csv_text, :headers => true, :header_converters=> lambda {|f| f.downcase.strip})
			
			custom_field_required = @tracker.custom_fields.blank? ? [] : @tracker.custom_fields.select(&:is_required).pluck(:name)
			tracker_log.info("======> custom_field_required:  #{custom_field_required} <=========")
			
			custom_field_names = @tracker.custom_fields.pluck(:name).reject(&:blank?)
			tracker_log.info("======> custom_field_names:  #{custom_field_names} <=========")
			# checking all required fields for creating issues
			(["subject", "status","priority",'author'] + custom_field_required.reject(&:blank?)).each{|name| @errors[:column_missing].push("required field #{name} is missing into CSV file") unless csv.headers.include?(name.downcase.strip()) }
			unless @errors[:column_missing].blank?
				tracker_log.info("======> missing columns error:  #{@errors[:column_missing]} <=========")
				render :index
				return
			end
			custom_fields_with_ids = {}
			
			custom_field_names.each do |name|
				tracker_log.info("======> custom_fields name:  #{name} <=========")
				custom_field = IssueCustomField.find_by_id(name) || IssueCustomField.find_by_name(name)
				unless custom_field.nil?
					custom_fields_with_ids[name] = {} 
					custom_fields_with_ids[name]['id'] = custom_field.id 
					custom_fields_with_ids[name]['default_options'] = custom_field.possible_values if ["list", "dependent_list"].include?(custom_field.field_format)
				end
			end
			
			tracker_log.info("======> custom_fields required data :  #{custom_fields_with_ids} <=========")
			
			data = []
			csv.each_with_index do |row,index|
				new_data = {}
				if row['subject'].blank? || row['status'].blank? || row['priority'].blank?
					@errors[:data_missing].push("\#Row #{index + 2 } has missing required field data")
				else
					issue_status = @issue_status.detect{|x| x.id.to_s == row['status'].downcase.strip || x.name.downcase.strip == row['status'].downcase.strip}
					tracker_log.info("======> issue_status :  #{issue_status} <=========")

					priority = @priorities.detect{|x| x.id.to_s == row['priority'].downcase.strip || x.name.downcase.strip == row['priority'].downcase.strip}
					tracker_log.info("======> priority:  #{priority} <=========")

					assignee = @users.detect{|x| x.id.to_s == row['author'].downcase.strip || x.firstname.downcase.strip == row['author'].downcase.strip || x.lastname.downcase.strip == row['author'].downcase.strip || "#{x.firstname} #{x.lastname}".downcase.strip == row['author'].downcase.strip || x.login.downcase.strip == row['author'].downcase.strip}
					tracker_log.info("======> assignee:  #{assignee} <=========")

					watchers = User.where(id: row['watcher']) || User.where(mail: row['watcher']) || User.where(firstname: row['watcher']) || User.select{|a| row['watcher'].include?(a.name) }
					tracker_log.info("======> watchers:  #{watchers} <=========")

					category = @categories.detect{|x| x.id.to_s == row['category'].downcase.strip || x.name.downcase.strip == row['category'].downcase.strip} 
					tracker_log.info("======> category:  #{category} <=========")

					author = @users.detect{|x| x.id.to_s == row['author'].downcase.strip || x.firstname.downcase.strip == row['author'].downcase.strip || x.lastname.downcase.strip == row['author'].downcase.strip || "#{x.firstname} #{x.lastname}".downcase.strip == row['author'].downcase.strip || x.login.downcase.strip == row['author'].downcase.strip}
					tracker_log.info("======> author:  #{author} <=========")

					if !priority.nil? && !issue_status.nil? && !author.nil?
						new_data['subject'] = row['subject']
						new_data['description'] = row['description']
						new_data['due_date'] = row['due_date'] unless row['due_date'].blank?
						new_data['category_id'] = category.id unless category.nil?
						new_data['status_id'] = issue_status.id
						new_data['assigned_to_id'] = assignee.id unless assignee.nil?
						new_data['priority_id'] = priority.id
						new_data['fixed_version_id'] = row['fixed_version_id']
						new_data['start_date'] = row['start_date'] unless row['start_date'].blank?
						new_data['done_ratio'] = row['done_ratio'] unless row['done_ratio'].blank?
						new_data['estimated_hours'] = row['estimated_hours'] unless row['estimated_hours'].blank?
						new_data['is_private'] = row['private'] unless row['private'].blank?
						new_data['project_id'] = project_id
						new_data['author_id'] = author.id
						new_data['parent_id'] = parent_id if parent_id.present?
						new_data['tracker_id'] = @tracker.id if @tracker.present?
						new_data['watcher_user_ids'] = watchers.map(&:id) if watchers.present?
						new_data["custom_field_values"]= {}
						custom_fields_with_ids.each do |key,value|
							if row[key.downcase.strip].present?
								tracker_log.info("======> custom field vales:  #{value} <=========")

								tracker_log.info("======> csv field vales:  #{row[key.downcase.strip]} <=========")

								tracker_log.info("======> custom field default_options:  #{value["default_options"] if value['default_options'].present?} <=========")

								new_input_value = value["default_options"].present? ?  value["default_options"].detect{|a| a.downcase.strip == row[key.downcase.strip].downcase.strip } : row[key.downcase.strip]

								tracker_log.info("======> custom value:  #{new_input_value} <=========")
								unless new_input_value.blank?
									new_data["custom_field_values"][value['id'].to_s] = new_input_value
								end
							end
						end

						data.push(new_data)
						tracker_log.info("======> new data of \#Row #{index + 2 }:  #{new_data} <=========")
					else
						@errors[:message].push("\#Row #{index + 2 } priority field value doesn't exist in database") if priority.nil?
						@errors[:message].push("\#Row #{index + 2 } author field value doesn't exist in database") if author.nil?
						@errors[:message].push("\#Row #{index + 2 } status field value doesn't exist in database") if issue_status.nil?
					end
				end
			end
			if @errors[:message].blank? && @errors[:column_missing].blank? && @errors[:data_missing].blank?
				begin
					tracker_log.info("======> data to create:  #{data} <=========")
					@issues = Issue.create!(data)	

					# sqs = Aws::SQS::Client.new(region: 'us-east-1')

					# Send a message to a queue.
					# queue_name = "Tracker_tasks"

					# begin
					# 	tracker_log.info("======> Queue Name:  #{queue_name} <=========")
					#   queue_url = sqs.get_queue_url(queue_name: queue_name).queue_url

					# 	tracker_log.info("======> Queue URl:  #{queue_url} <=========")

					#   # Create a message with three custom attributes: Title, Author, and WeeksOn.
					#   send_message_result = sqs.send_message({
					#     queue_url: queue_url, 
					#     message_body: "Adding tasks to the tracker.",
					#     message_attributes: data.to_json
					#   })
					# 	tracker_log.info("======> Send Message Result:  #{send_message_result} <=========")
					# rescue Aws::SQS::Errors::NonExistentQueue
					# 	tracker_log.info("======> SDK Queue Error: A queue named #{queue_name} does not exist. <=========")
					#   puts 
					#   exit(false)
					# end
					# 	tracker_log.info("======> Message ID #{send_message_result.message_id} <=========")

					# puts send_message_result.message_id

					# Receive the message in the queue.
					# receive_message_result = sqs.receive_message({
					#   queue_url: queue_url, 
					#   message_attribute_names: ["All"], # Receive all custom attributes.
					#   max_number_of_messages: 1, # Receive at most one message.
					#   wait_time_seconds: 0 # Do not wait to check for the message.
					# })

					# Display information about the message.
					# Display the message's body and each custom attribute value.
					# receive_message_result.messages.each do |message|
					#   puts message.body 
					#   puts "Title: #{message.message_attributes["Title"]["string_value"]}"
					#   puts "Author: #{message.message_attributes["Author"]["string_value"]}"
					#   puts "WeeksOn: #{message.message_attributes["WeeksOn"]["string_value"]}"  
	

app/helpers/tracker_management_actions_helper.rb
module TrackerManagementActionsHelper
end

app/views/tracker_management_actions/index.html.erb
<% content_for :header_tags do %>
<%= stylesheet_link_tag 'tracker_action', plugin: 'tracker_management' %>
<%= javascript_include_tag 'tracker_action', plugin: 'tracker_management' %>
<% end %>
<div class="container-fluid">
    <div class="row">
        <div class="col-main-section">
            <div class="row">
                <!-- <div class="col-left-section">
                    <ul>
                        <li>
                            <%#= link_to 'Define Action',tracker_action_path %>
                        </li>
                        <li>
                            <%#= link_to 'Bulk Upload',tracker_actions_path %>
                        </li>
                    </ul>
                </div> -->
                <div class="col-right-section tracker-action-table">
                    <%if @errors.present? && @errors[:message].present? %>
                      <div id="errorExplanation"><ul>
                        <%@errors[:message].each do |msg|%>
                          <li><%= msg %></li>
                        <%end%>
                      </ul></div>
                    <%end%>
                    <form id="Bulk_Upload" class="tracker-action-form" action="<%= create_csvfile_tracker_path%>" method="POST" enctype="multipart/form-data">
                        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token%>">
                        <h2>Bulk Upload</h2>
                        <!-- <label for="tracker_action_name">Action Name</label> -->
                        <label for="tracker_action_project"> Select Project</label>
                        <select id="tracker_action_project" name="tracker_action[project_id]" data-selected-option="<%=params[:tracker_action][:project_id] if params[:tracker_action].present? %>" data-type="project" required="true">
                            <option value="" disabled selected>Please select project</option>
                            <% @projects.each do |project| %>
                              <option value="<%= project.id %>"><%= project.try(:name) %></option>
                            <% end %>
                        </select>
                        </br>
                        <label for="tracker_action_tracker">Select Tracker</label>
                        <select id="tracker_action_tracker" data-type="tracker" data-selected-option="<%= params[:tracker_action][:tracker_id] if params[:tracker_action] %>" name="tracker_action[tracker_id]" required="true">
                            <option value="" disabled selected>Please select tracker</option>
                        </select>
                        </br>
                        <!-- <label for="parent_tracker_task">Select Parent task</label>
                        <input id="parent_tracker_task" data-type="parent-tracker-task"> -->
                        <input id="parent-task-value" type="hidden" name="tracker_action[parent_id]" value="<%= params[:parent_id] if params[:parent_id].present? %>">
                            
                        </br>
                        <label for="tracker_csv_file">Select Excel/Csv File</label>
                        <input id="tracker_csv_file" type="file" name="tracker_action[file]" data-type="csv_file" >
                        </br>
                        <dir class="row">
                          <%if @errors.present? && !@errors[:column_missing].blank?%>
                            <div class="errorExplanation missing_column">
                              <%@errors[:column_missing].each do |msg|%>
                                <ul>
                                  <li><%= msg %> </li>
                                </ul>
                              <%end%>
                            </div>
                          <%end%>
                          <%if @errors.present? && !@errors[:data_missing].blank?%>
                            <div class="errorExplanation data_missing">
                              <%@errors[:data_missing].each do |msg|%>
                                <ul>
                                  <li><%= msg %> </li>
                                </ul>
                              <%end%>
                            </div>
                          <%end%>
                        </dir>
                          </br>
                        <div class="inline-flex">
                            <button class="btn"> Save</button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>